name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release Slugger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Perform release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}