name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    name: Release Slugger
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Temporarily disable branch protection
        uses: benjefferies/branch-protection-bot@v1.0.5
        with:
          access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Perform release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_release: 17.0.4
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      - name: Re-enable branch protection
        uses: benjefferies/branch-protection-bot@v1.0.5
        if: always()  # Force to always run this step to ensure "include administrators" is turned back on
        with:
          access-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}